### PR TITLE
Checking For Network Connection Offline

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/gitea-react-toolkit/21)

### CODE REVIEW

**Comment by klappy** [comment]
___
*[src/components/authentication/Authentication.js, line 79 at r2](https://reviewable.io/reviews/unfoldingword/gitea-react-toolkit/21#-LzhEx6q0GBPYzouU7qD:-LzhEx6r7WUHiSpMpqK4:b-97g1gi) ([raw file](https://github.com/unfoldingword/gitea-react-toolkit/blob/937671e663c5b7e1da7a55d9cad3b0475e595b49/src/components/authentication/Authentication.js#L79)):*
> ```JavaScript
>         
>         if (errorMessage.match(/ERR_INTERNET_DISCONNECTED/ig)) {
>           return setError('There is an issue with your network connection. Please try again.');
> ```

Can we pass this error in with messages with a default like the other error messages?

**Comment by klappy** [comment]
___
*[src/core/gitea-api/users/users.ts, line 19 at r2](https://reviewable.io/reviews/unfoldingword/gitea-react-toolkit/21#-LzhF6k18No7_Kv_LxGB:-LzhF6k18No7_Kv_LxGC:b-iqp9u7) ([raw file](https://github.com/unfoldingword/gitea-react-toolkit/blob/937671e663c5b7e1da7a55d9cad3b0475e595b49/src/core/gitea-api/users/users.ts#L19)):*
> ```XML
> 
>     if (!errorResponse && errorMessage.match(/network/ig) && !navigator.onLine) {
>       throw new Error('ERR_INTERNET_DISCONNECTED');
> ```

This is a good error to catch but I think it doesn't address the issue we were encountering. We need to somehow test for the server not being available even when we have an internet connection. I'm not entirely sure the best way to handle this.

**Comment by klappy** [comment]
___
*[src/core/gitea-api/users/users.ts, line 19 at r2](https://reviewable.io/reviews/unfoldingword/gitea-react-toolkit/21#-LzhF6k18No7_Kv_LxGB:-LzhZ3ZC7onQGBuANiSx:b-r044rr) ([raw file](https://github.com/unfoldingword/gitea-react-toolkit/blob/937671e663c5b7e1da7a55d9cad3b0475e595b49/src/core/gitea-api/users/users.ts#L19)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Yes, you are right I realized when you were speaking about the issue that I need to do another implementation. I did some research and it seems from the axios community that checking for `error.response` being defined is the way to go https://github.com/axios/axios/issues/383#issuecomment-316501886 so maybe do not need `navigator.onLine` or can have a separate error for `navigator.onLine`
</blockquote></details>

I like the existing error you are catching. I think we can add a new one for seeing if the `config.server` url is available. So two errors, online/offline and if the git.door43.org (or what ever is in the config) server is up and running.

**Comment by klappy** [comment]
___
*[src/core/gitea-api/users/users.ts, line 19 at r2](https://reviewable.io/reviews/unfoldingword/gitea-react-toolkit/21#-LzhF6k18No7_Kv_LxGB:-LzlFONW3Fz8Zy5yD1o0:b-9xwos7) ([raw file](https://github.com/unfoldingword/gitea-react-toolkit/blob/937671e663c5b7e1da7a55d9cad3b0475e595b49/src/core/gitea-api/users/users.ts#L19)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Ok, couldn't find anything in the swagger docs for checking status, I think checking if it responds with a response is good enough for now. Let me know. And I kept them in the same if block for network error so that it will a little more specific but still generic for now until we find that we need a more specific error message
</blockquote></details>

The heart of the story is misleading error messages. 
When the user tried to log in and DCS was down, and the user still had an internet connection, it was telling them that their username was invalid. 

This PR added a check for whether the internet connection is up or not but still has the same behavior as before in the use case stated in the story.
To test this, change the server url in the authentication example to a server that does not exist, and when trying to log in, it tells you that the user does not exist.

We need a way to tell the user if the server is not responding in addition to whether or not the internet is connected.
One possible way is to make a get request to the domain, there is a good chance that the domain homepage will respond with a non-error result if the server is up.
This can be done in the catch here as to not have to run the check every time, but just when this block catches an error requesting the user.

**Comment by klappy** [comment]
___
*[src/core/gitea-api/users/users.ts, line 19 at r2](https://reviewable.io/reviews/unfoldingword/gitea-react-toolkit/21#-LzhF6k18No7_Kv_LxGB:-LzmS9nD3_VIl-ab5G-l:b-ovwaw7) ([raw file](https://github.com/unfoldingword/gitea-react-toolkit/blob/937671e663c5b7e1da7a55d9cad3b0475e595b49/src/core/gitea-api/users/users.ts#L19)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

I will ask rich and see is there a way to check the server status through an API call
</blockquote></details>

Good idea.

**Comment by klappy** [comment]
___
*[src/core/gitea-api/users/users.ts, line 19 at r2](https://reviewable.io/reviews/unfoldingword/gitea-react-toolkit/21#-LzhF6k18No7_Kv_LxGB:-M-1Y5YD2WU33BtzQNc4:bbw6nsf) ([raw file](https://github.com/unfoldingword/gitea-react-toolkit/blob/937671e663c5b7e1da7a55d9cad3b0475e595b49/src/core/gitea-api/users/users.ts#L19)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Good idea.
</blockquote></details>

For some reason no matter what I do trying to test these edge cases the only error that is reported is that no user is found. 
Looking at the code I'm not seeing why it reports that instead of the server being unreachable or no internet connection.
It looks as if the errors are being swallowed and user is being returned as null even if those errors are thrown.

**Comment by klappy** [comment]
___
*[src/core/gitea-api/users/users.ts, line 19 at r2](https://reviewable.io/reviews/unfoldingword/gitea-react-toolkit/21#-LzhF6k18No7_Kv_LxGB:-M-BuVSI14d2bBGtp0nB:be4b5t7) ([raw file](https://github.com/unfoldingword/gitea-react-toolkit/blob/937671e663c5b7e1da7a55d9cad3b0475e595b49/src/core/gitea-api/users/users.ts#L19)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

I had to add the error messages to the mdx example. Should be working now! :)
</blockquote></details>

The messages in the .mdx files are just overrides for the string value and shouldn't affect its ability to throw the proper errors.  

Can you send me a screenshot of the errors being thrown? I can't seem to do so.

**Comment by RoyalSix** [comment]
Screen Shot 2020-02-04 at 7 48 53 AM (2)
Screen Shot 2020-02-04 at 7 50 20 AM (2)

@klappy Second screen shot is after turning off the network connection in the dev tools. Also it looks like its a cached response, so you will not get the correct error message in some instances. I am wondering if it is better to not use the cache

**Comment by klappy** [comment]
___
*[src/core/gitea-api/users/users.ts, line 19 at r2](https://reviewable.io/reviews/unfoldingword/gitea-react-toolkit/21#-LzhF6k18No7_Kv_LxGB:-M-GPKQ4ACRJIJUqc8OX:b-c08gbi) ([raw file](https://github.com/unfoldingword/gitea-react-toolkit/blob/937671e663c5b7e1da7a55d9cad3b0475e595b49/src/core/gitea-api/users/users.ts#L19)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

The messages in the .mdx files are just overrides for the string value and shouldn't affect its ability to throw the proper errors.  

Can you send me a screenshot of the errors being thrown? I can't seem to do so.
</blockquote></details>

**Comment by klappy** [comment]
___
*[src/core/gitea-api/users/users.ts, line 19 at r2](https://reviewable.io/reviews/unfoldingword/gitea-react-toolkit/21#-LzhF6k18No7_Kv_LxGB:-M-LMCR85_G6ZDqxv4D-:b2o0i45) ([raw file](https://github.com/unfoldingword/gitea-react-toolkit/blob/937671e663c5b7e1da7a55d9cad3b0475e595b49/src/core/gitea-api/users/users.ts#L19)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>


</blockquote></details>

Okay, Errors look good now!

**Comment by klappy** [comment]
___
*[cypress/integration/authentication.spec.js, line 6 at r7](https://reviewable.io/reviews/unfoldingword/gitea-react-toolkit/21#-M-LMa_1ALOoFjfd437M:-M-LMa_27DIefewKU11T:bpmvlpd) ([raw file](https://github.com/unfoldingword/gitea-react-toolkit/blob/3b94269a6ffdfd1867ef5134bbf1d766d29c22ed/cypress/integration/authentication.spec.js#L6)):*
> ```JavaScript
>     cy.clearLocalStorage();
>   });
>   it('should not login with incorrect password', function () {
> ```

Would it be hard to write new tests for our new errors?

**Comment by klappy** [comment]
___
*[src/components/authentication/Authentication.js, line 129 at r7](https://reviewable.io/reviews/unfoldingword/gitea-react-toolkit/21#-M-LMoiE7vaeT7ryJbcr:-M-LMoiE7vaeT7ryJbcs:b-pk2u1d) ([raw file](https://github.com/unfoldingword/gitea-react-toolkit/blob/af0fb56a7d808d5e4c8bdf13e0db4e2c3b143387/src/components/authentication/Authentication.js#L129)):*
> ```JavaScript
> };
> 
> Authentication.defaultProps = {
> ```

Don't forget to move default props to the top of the file at the deconstruction of props object in the function definition.

**Pull request merged**
