### PR TITLE
Katalon:ID required for the close button

### PR DESCRIPTION
**Pull request by Joel-C-Johnson**
- [x] Added Katalon Id for the close button in header bar
- [x] able to close chip even when the file is not selected

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/gitea-react-toolkit/112)

### CODE REVIEW

**Review by jincypjose — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/gitea-react-toolkit/112)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elsylambert)

**Comment by jincypjose** [comment]
Have approved the PR.Saw you gave id to the button.

**Comment by Joel-C-Johnson** [comment]
@elsylambert, I have added the id to the chip close icon. Can you test it in Katalon,
Demo Link : https://tc-create-app-test.netlify.app/

**Review by jincypjose — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/gitea-react-toolkit/112)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elsylambert)

**Pull request merged**
