### PR TITLE
WIP for issue 244

### PR DESCRIPTION
**Pull request by mandolyte**
Work in progress... needs review and feedback.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/gitea-react-toolkit/46)

### CODE REVIEW

**Comment by mandolyte** [comment]
Note: most of the changes are in the typescript file `orgs.ts`... it does slow it down a bit due the verification made via the extra Gitea API calls.

**Comment by ancientTexts-net** [comment]
___
*[src/components/organization/Organization.js, line 60 at r2](https://reviewable.io/reviews/unfoldingword/gitea-react-toolkit/46#-MDylZ_pCMTjrwjz-03T:-MDylZ_pCMTjrwjz-03U:b-1uoicg) ([raw file](https://github.com/unfoldingword/gitea-react-toolkit/blob/ebcf22f2f344b22bdf112dc3b374b40e36a94c95/src/components/organization/Organization.js#L60)):*
> ```JavaScript
> 
>   const _onOrganization = useCallback(async () => {
> ```

Should we refactor the API call into a helper method, please?
Does a standard helper for gitea API calls already exist in GRT?  I'm unsure.  Thank you!

**Comment by ancientTexts-net** [comment]
___
*[src/core/gitea-api/users/orgs/orgs.ts, line 14 at r2](https://reviewable.io/reviews/unfoldingword/gitea-react-toolkit/46#-MDylq5L01GANTJVy6Ic:-MDylq5L01GANTJVy6Id:b-re0gxa) ([raw file](https://github.com/unfoldingword/gitea-react-toolkit/blob/ebcf22f2f344b22bdf112dc3b374b40e36a94c95/src/core/gitea-api/users/orgs/orgs.ts#L14)):*
> ```XML
>   visibility: string;
>   website: string;
>   permission?: string;
> ```

Cool idea to have `permission` extensible!  Good thinking

**Comment by mandolyte** [comment]
@ancientTexts-net completed move of low level API logic to `core/gitea/users/orgs/orgs.ts`.

Ready for review.

**Comment by ancientTexts-net** [comment]
:lgtm:

thank you for refactoring the API calls!  great work as always

**Pull request merged**
