### PR TITLE
tooltip and fix deploy of styleguidest

### PR DESCRIPTION
**Pull request by mandolyte**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/gitea-react-toolkit/28)

### CODE REVIEW

**Comment by mandolyte** [comment]
@klappy @RoyalSix Note especially the changes to `package.json`. Did not find a script there to deploy GH pages, so I added.

How was this done before? I see there is a gh-pages branch for it!

**Comment by RoyalSix** [comment]
@mandolyte Is there a list of all the tool tips I should be checking for?

**Comment by RoyalSix** [comment]
@mandolyte Tooltip UI looks great!

**Comment by klappy** [comment]
___
*[package.json, line 17 at r1](https://reviewable.io/reviews/unfoldingword/gitea-react-toolkit/28#-M4zhkuV332M8Sbx6orQ:-M4zhkuWDdsXWsWfHKs2:b-h7uyt0) ([raw file](https://github.com/unfoldingword/gitea-react-toolkit/blob/60fd66ff99a3c99ad659d40cfe22aff64e0bf347/package.json#L17)):*
> ```JSON
>     "axios-cache-adapter": "2.4.1",
>     "base-64": "0.1.0",
>     "gh-pages": "^2.2.0",
> ```

We're using Netlify's auto deployment. It doesn't require gh-pages.

**Comment by klappy** [comment]
___
*[package.json, line 27 at r1](https://reviewable.io/reviews/unfoldingword/gitea-react-toolkit/28#-M4zhzRn8Yp0XYo867ve:-M4zhzRn8Yp0XYo867vf:b-1c3zc3) ([raw file](https://github.com/unfoldingword/gitea-react-toolkit/blob/60fd66ff99a3c99ad659d40cfe22aff64e0bf347/package.json#L27)):*
> ```JSON
>     "start": "styleguidist server",
>     "build": "styleguidist build",
>     "styleguide:build": "styleguidist build",
> ```

We can remove these scripts as well since Netlify handles this for us.

**Comment by mandolyte** [comment]
See the Zulip #Software ToolTip Text stream. Elsy is identifying them as
she does QA work.

Blessings,
Cecil

**Comment by mandolyte** [comment]
@klappy If I use gh-pages, I can put my changes out for @elsy to review them. I can even do this without updating my feature branch. I thought this was a good way to let others see the changes before committing to them. Of course, I can just run the commands without putting the scripts in `package.json`.

But it sounds like there may be another path to this goal using netlify? 

Thoughts?

@RoyalSix what is `crowdin`?

**Comment by RoyalSix** [comment]
@mandolyte Not sure if you are looking for another use case but when you push to a PR branch on netlify it triggers a build on a unique url. This build shows on the github checks. In this case it is https://deploy-preview-28--gitea-react-toolkit.netlify.app/

crowdin is a way to get others to contribute to localization strings without being involved with the development process. they have an api as well that will create PR's whenever new translations are published. This is the workflow tC uses. Not something I expect in this issue, just something we can build towards in the future.

**Comment by mandolyte** [comment]
Thanks Jay. I'll check crowdin out, just understand it better

**Pull request merged**
